// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cod.proto

package cod

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_ValueInt
	//	*Value_ValueFloat
	//	*Value_ValueString
	Value                isValue_Value `protobuf_oneof:"Value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_8364499d937b9ed7, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_ValueInt struct {
	ValueInt int32 `protobuf:"varint,1,opt,name=value_int,json=valueInt,proto3,oneof"`
}

type Value_ValueFloat struct {
	ValueFloat float32 `protobuf:"fixed32,2,opt,name=value_float,json=valueFloat,proto3,oneof"`
}

type Value_ValueString struct {
	ValueString string `protobuf:"bytes,3,opt,name=value_string,json=valueString,proto3,oneof"`
}

func (*Value_ValueInt) isValue_Value() {}

func (*Value_ValueFloat) isValue_Value() {}

func (*Value_ValueString) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetValueInt() int32 {
	if x, ok := m.GetValue().(*Value_ValueInt); ok {
		return x.ValueInt
	}
	return 0
}

func (m *Value) GetValueFloat() float32 {
	if x, ok := m.GetValue().(*Value_ValueFloat); ok {
		return x.ValueFloat
	}
	return 0
}

func (m *Value) GetValueString() string {
	if x, ok := m.GetValue().(*Value_ValueString); ok {
		return x.ValueString
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_ValueInt)(nil),
		(*Value_ValueFloat)(nil),
		(*Value_ValueString)(nil),
	}
}

type ArrayValue struct {
	Value                []*Value `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArrayValue) Reset()         { *m = ArrayValue{} }
func (m *ArrayValue) String() string { return proto.CompactTextString(m) }
func (*ArrayValue) ProtoMessage()    {}
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_8364499d937b9ed7, []int{1}
}

func (m *ArrayValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayValue.Unmarshal(m, b)
}
func (m *ArrayValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayValue.Marshal(b, m, deterministic)
}
func (m *ArrayValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayValue.Merge(m, src)
}
func (m *ArrayValue) XXX_Size() int {
	return xxx_messageInfo_ArrayValue.Size(m)
}
func (m *ArrayValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayValue.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayValue proto.InternalMessageInfo

func (m *ArrayValue) GetValue() []*Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Variable struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Variable_ValueInt
	//	*Variable_ValueFloat
	//	*Variable_ValueString
	//	*Variable_ValueArray
	Value                isVariable_Value `protobuf_oneof:"Value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Variable) Reset()         { *m = Variable{} }
func (m *Variable) String() string { return proto.CompactTextString(m) }
func (*Variable) ProtoMessage()    {}
func (*Variable) Descriptor() ([]byte, []int) {
	return fileDescriptor_8364499d937b9ed7, []int{2}
}

func (m *Variable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Variable.Unmarshal(m, b)
}
func (m *Variable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Variable.Marshal(b, m, deterministic)
}
func (m *Variable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Variable.Merge(m, src)
}
func (m *Variable) XXX_Size() int {
	return xxx_messageInfo_Variable.Size(m)
}
func (m *Variable) XXX_DiscardUnknown() {
	xxx_messageInfo_Variable.DiscardUnknown(m)
}

var xxx_messageInfo_Variable proto.InternalMessageInfo

func (m *Variable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isVariable_Value interface {
	isVariable_Value()
}

type Variable_ValueInt struct {
	ValueInt int32 `protobuf:"varint,2,opt,name=value_int,json=valueInt,proto3,oneof"`
}

type Variable_ValueFloat struct {
	ValueFloat float32 `protobuf:"fixed32,3,opt,name=value_float,json=valueFloat,proto3,oneof"`
}

type Variable_ValueString struct {
	ValueString string `protobuf:"bytes,4,opt,name=value_string,json=valueString,proto3,oneof"`
}

type Variable_ValueArray struct {
	ValueArray *ArrayValue `protobuf:"bytes,5,opt,name=value_array,json=valueArray,proto3,oneof"`
}

func (*Variable_ValueInt) isVariable_Value() {}

func (*Variable_ValueFloat) isVariable_Value() {}

func (*Variable_ValueString) isVariable_Value() {}

func (*Variable_ValueArray) isVariable_Value() {}

func (m *Variable) GetValue() isVariable_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Variable) GetValueInt() int32 {
	if x, ok := m.GetValue().(*Variable_ValueInt); ok {
		return x.ValueInt
	}
	return 0
}

func (m *Variable) GetValueFloat() float32 {
	if x, ok := m.GetValue().(*Variable_ValueFloat); ok {
		return x.ValueFloat
	}
	return 0
}

func (m *Variable) GetValueString() string {
	if x, ok := m.GetValue().(*Variable_ValueString); ok {
		return x.ValueString
	}
	return ""
}

func (m *Variable) GetValueArray() *ArrayValue {
	if x, ok := m.GetValue().(*Variable_ValueArray); ok {
		return x.ValueArray
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Variable) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Variable_ValueInt)(nil),
		(*Variable_ValueFloat)(nil),
		(*Variable_ValueString)(nil),
		(*Variable_ValueArray)(nil),
	}
}

type Variables struct {
	Variable             []*Variable `protobuf:"bytes,1,rep,name=variable,proto3" json:"variable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Variables) Reset()         { *m = Variables{} }
func (m *Variables) String() string { return proto.CompactTextString(m) }
func (*Variables) ProtoMessage()    {}
func (*Variables) Descriptor() ([]byte, []int) {
	return fileDescriptor_8364499d937b9ed7, []int{3}
}

func (m *Variables) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Variables.Unmarshal(m, b)
}
func (m *Variables) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Variables.Marshal(b, m, deterministic)
}
func (m *Variables) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Variables.Merge(m, src)
}
func (m *Variables) XXX_Size() int {
	return xxx_messageInfo_Variables.Size(m)
}
func (m *Variables) XXX_DiscardUnknown() {
	xxx_messageInfo_Variables.DiscardUnknown(m)
}

var xxx_messageInfo_Variables proto.InternalMessageInfo

func (m *Variables) GetVariable() []*Variable {
	if m != nil {
		return m.Variable
	}
	return nil
}

type Object struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Variables            *Variables `protobuf:"bytes,2,opt,name=variables,proto3" json:"variables,omitempty"`
	Objects              []*Object  `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_8364499d937b9ed7, []int{4}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Object) GetVariables() *Variables {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *Object) GetObjects() []*Object {
	if m != nil {
		return m.Objects
	}
	return nil
}

type Objects struct {
	Object               []*Object `protobuf:"bytes,1,rep,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Objects) Reset()         { *m = Objects{} }
func (m *Objects) String() string { return proto.CompactTextString(m) }
func (*Objects) ProtoMessage()    {}
func (*Objects) Descriptor() ([]byte, []int) {
	return fileDescriptor_8364499d937b9ed7, []int{5}
}

func (m *Objects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Objects.Unmarshal(m, b)
}
func (m *Objects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Objects.Marshal(b, m, deterministic)
}
func (m *Objects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Objects.Merge(m, src)
}
func (m *Objects) XXX_Size() int {
	return xxx_messageInfo_Objects.Size(m)
}
func (m *Objects) XXX_DiscardUnknown() {
	xxx_messageInfo_Objects.DiscardUnknown(m)
}

var xxx_messageInfo_Objects proto.InternalMessageInfo

func (m *Objects) GetObject() []*Object {
	if m != nil {
		return m.Object
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "cod.Value")
	proto.RegisterType((*ArrayValue)(nil), "cod.ArrayValue")
	proto.RegisterType((*Variable)(nil), "cod.Variable")
	proto.RegisterType((*Variables)(nil), "cod.Variables")
	proto.RegisterType((*Object)(nil), "cod.Object")
	proto.RegisterType((*Objects)(nil), "cod.Objects")
}

func init() { proto.RegisterFile("cod.proto", fileDescriptor_8364499d937b9ed7) }

var fileDescriptor_8364499d937b9ed7 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4a, 0xf4, 0x30,
	0x14, 0xc5, 0x27, 0xd3, 0xe9, 0xbf, 0xdb, 0xef, 0x53, 0xc8, 0x2a, 0x1b, 0x21, 0x76, 0x10, 0x2a,
	0x48, 0x17, 0x15, 0xdc, 0xeb, 0x42, 0xea, 0x4a, 0x88, 0x30, 0x5b, 0x49, 0x3b, 0x55, 0x2a, 0xb5,
	0xd1, 0x36, 0x8e, 0xf8, 0x7a, 0x3e, 0x99, 0xf4, 0x26, 0x9d, 0x52, 0x18, 0xd0, 0x5d, 0x7a, 0xce,
	0xbd, 0xe7, 0x9e, 0x1f, 0x14, 0xc2, 0x52, 0x6d, 0xd3, 0xb7, 0x4e, 0x69, 0x45, 0x9d, 0x52, 0x6d,
	0xe3, 0x4f, 0x70, 0x37, 0xb2, 0xf9, 0xa8, 0xe8, 0x09, 0x84, 0xbb, 0xe1, 0xf1, 0x58, 0xb7, 0x9a,
	0x11, 0x4e, 0x12, 0x37, 0x5f, 0x88, 0x00, 0xa5, 0xbb, 0x56, 0xd3, 0x53, 0x88, 0x8c, 0xfd, 0xd4,
	0x28, 0xa9, 0xd9, 0x92, 0x93, 0x64, 0x99, 0x2f, 0x04, 0xa0, 0x78, 0x3b, 0x68, 0x74, 0x0d, 0xff,
	0xcc, 0x48, 0xaf, 0xbb, 0xba, 0x7d, 0x66, 0x0e, 0x27, 0x49, 0x98, 0x2f, 0x84, 0x59, 0x7c, 0x40,
	0xf1, 0xc6, 0xb7, 0xf7, 0xe2, 0x14, 0xe0, 0xba, 0xeb, 0xe4, 0x97, 0xb9, 0xce, 0xc1, 0xc5, 0x29,
	0x46, 0xb8, 0x93, 0x44, 0x19, 0xa4, 0x43, 0x4d, 0xb4, 0x84, 0x31, 0xe2, 0x6f, 0x02, 0xc1, 0x46,
	0x76, 0xb5, 0x2c, 0x9a, 0x8a, 0x52, 0x58, 0xb5, 0xf2, 0xb5, 0xc2, 0x9e, 0xa1, 0xc0, 0xf7, 0x1c,
	0x60, 0xf9, 0x1b, 0x80, 0xf3, 0x07, 0x80, 0xd5, 0x01, 0x00, 0x9a, 0x8d, 0x39, 0x72, 0x68, 0xcf,
	0x5c, 0x4e, 0x92, 0x28, 0x3b, 0xc6, 0xbe, 0x13, 0xcf, 0x3e, 0x18, 0xa5, 0x09, 0xfa, 0x0a, 0xc2,
	0x91, 0xa1, 0xa7, 0xe7, 0x10, 0xec, 0xec, 0x87, 0xc5, 0xfe, 0x6f, 0xb1, 0x8d, 0x28, 0xf6, 0x76,
	0xfc, 0x0e, 0xde, 0x7d, 0xf1, 0x52, 0x95, 0xfa, 0x20, 0xf9, 0xc5, 0x40, 0x6e, 0x53, 0x91, 0x3c,
	0xca, 0x8e, 0x66, 0x49, 0xbd, 0x98, 0x06, 0xe8, 0x19, 0xf8, 0x0a, 0xb3, 0x7a, 0xe6, 0xe0, 0xd5,
	0x08, 0x67, 0x4d, 0xbe, 0x18, 0xbd, 0x38, 0x05, 0xdf, 0x48, 0x3d, 0x5d, 0x83, 0x67, 0x54, 0x5b,
	0x73, 0xb6, 0x60, 0xad, 0xc2, 0xc3, 0x9f, 0xea, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0xef, 0xcd,
	0xb1, 0x8c, 0x61, 0x02, 0x00, 0x00,
}
